//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider.OperationsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com/fr/gazdefrance/negoce/signal/ws/administration/operations", ConfigurationName="OperationsService.ExtractionOperationsWS")]
    public interface ExtractionOperationsWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FXWIN.Data.Provider.OperationsService.GetListOperationsOutput getListOperations(FXWIN.Data.Provider.OperationsService.GetListOperationsInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<FXWIN.Data.Provider.OperationsService.GetListOperationsOutput> getListOperationsAsync(FXWIN.Data.Provider.OperationsService.GetListOperationsInput input);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.xb.signal")]
    public partial class GetListOperationsInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string principalField;
        
        private string subjectField;
        
        private string codeProgrammeField;
        
        private System.Nullable<System.DateTime> dateDebutField;
        
        private System.Nullable<System.DateTime> dateFinField;
        
        private string codeNavireField;
        
        private string operationsInternesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
                this.RaisePropertyChanged("principal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codeProgramme {
            get {
                return this.codeProgrammeField;
            }
            set {
                this.codeProgrammeField = value;
                this.RaisePropertyChanged("codeProgramme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> dateDebut {
            get {
                return this.dateDebutField;
            }
            set {
                this.dateDebutField = value;
                this.RaisePropertyChanged("dateDebut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dateFin {
            get {
                return this.dateFinField;
            }
            set {
                this.dateFinField = value;
                this.RaisePropertyChanged("dateFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string codeNavire {
            get {
                return this.codeNavireField;
            }
            set {
                this.codeNavireField = value;
                this.RaisePropertyChanged("codeNavire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string operationsInternes {
            get {
                return this.operationsInternesField;
            }
            set {
                this.operationsInternesField = value;
                this.RaisePropertyChanged("operationsInternes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dvt.com")]
    public partial class ReturnCodeItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RC_LEVEL levelField;
        
        private string messageField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RC_LEVEL level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:dvt.com")]
    public enum RC_LEVEL {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xb.signal")]
    public partial class ListOperations : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateOperationField;
        
        private string codeCargaisonField;
        
        private string codeNavireField;
        
        private string codeTerminalField;
        
        private string typeCargaisonField;
        
        private string typeOperationField;
        
        private string typeElementOperationField;
        
        private string codeContratField;
        
        private string codeCpVendeuseField;
        
        private string codeCpAcheteuseField;
        
        private string codeMiddleOfficeField;
        
        private float volumeOperationField;
        
        private float quantiteOperationField;
        
        private float volumePertesField;
        
        private float quantitePertesField;
        
        private string codeAbattementField;
        
        private string portChargementField;
        
        private int idCargaisonField;
        
        private System.DateTime heureOperationField;
        
        private decimal qteOperationBigDecField;
        
        private decimal qtePertesBigDecField;
        
        private int mefField;
        
        private string tpsMefMegField;
        
        private float volMefMegField;
        
        private float qteMefMegField;
        
        private decimal qteMefMegBigDecField;
        
        private string codeBookField;
        
        private float remportField;
        
        private float consoGNLField;
        
        private float consoCarbField;
        
        private float quantiteMaxField;
        
        private float robUACField;
        
        private float robUADField;
        
        private float robUDCField;
        
        private float quantiteCField;
        
        private float remportCField;
        
        private float consoGNLCField;
        
        private float consoCarbCField;
        
        private float quantiteMaxCField;
        
        private float robUACCField;
        
        private float robUADCField;
        
        private float robUDCCField;
        
        private float quantiteMField;
        
        private float remportMField;
        
        private float consoGNLMField;
        
        private float consoCarbMField;
        
        private float quantiteMaxMField;
        
        private float robUACMField;
        
        private float robUADMField;
        
        private float robUDCMField;
        
        private string canalSuezField;
        
        private string canalPanamaField;
        
        private string canalMagellanField;
        
        private System.DateTime dateSuezField;
        
        private System.DateTime datePanamaField;
        
        private System.DateTime dateMagellanField;
        
        private int idPositionCtrmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime dateOperation {
            get {
                return this.dateOperationField;
            }
            set {
                this.dateOperationField = value;
                this.RaisePropertyChanged("dateOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codeCargaison {
            get {
                return this.codeCargaisonField;
            }
            set {
                this.codeCargaisonField = value;
                this.RaisePropertyChanged("codeCargaison");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codeNavire {
            get {
                return this.codeNavireField;
            }
            set {
                this.codeNavireField = value;
                this.RaisePropertyChanged("codeNavire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string codeTerminal {
            get {
                return this.codeTerminalField;
            }
            set {
                this.codeTerminalField = value;
                this.RaisePropertyChanged("codeTerminal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string typeCargaison {
            get {
                return this.typeCargaisonField;
            }
            set {
                this.typeCargaisonField = value;
                this.RaisePropertyChanged("typeCargaison");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string typeOperation {
            get {
                return this.typeOperationField;
            }
            set {
                this.typeOperationField = value;
                this.RaisePropertyChanged("typeOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string typeElementOperation {
            get {
                return this.typeElementOperationField;
            }
            set {
                this.typeElementOperationField = value;
                this.RaisePropertyChanged("typeElementOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string codeContrat {
            get {
                return this.codeContratField;
            }
            set {
                this.codeContratField = value;
                this.RaisePropertyChanged("codeContrat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string codeCpVendeuse {
            get {
                return this.codeCpVendeuseField;
            }
            set {
                this.codeCpVendeuseField = value;
                this.RaisePropertyChanged("codeCpVendeuse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string codeCpAcheteuse {
            get {
                return this.codeCpAcheteuseField;
            }
            set {
                this.codeCpAcheteuseField = value;
                this.RaisePropertyChanged("codeCpAcheteuse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string codeMiddleOffice {
            get {
                return this.codeMiddleOfficeField;
            }
            set {
                this.codeMiddleOfficeField = value;
                this.RaisePropertyChanged("codeMiddleOffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public float volumeOperation {
            get {
                return this.volumeOperationField;
            }
            set {
                this.volumeOperationField = value;
                this.RaisePropertyChanged("volumeOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public float quantiteOperation {
            get {
                return this.quantiteOperationField;
            }
            set {
                this.quantiteOperationField = value;
                this.RaisePropertyChanged("quantiteOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public float volumePertes {
            get {
                return this.volumePertesField;
            }
            set {
                this.volumePertesField = value;
                this.RaisePropertyChanged("volumePertes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public float quantitePertes {
            get {
                return this.quantitePertesField;
            }
            set {
                this.quantitePertesField = value;
                this.RaisePropertyChanged("quantitePertes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string codeAbattement {
            get {
                return this.codeAbattementField;
            }
            set {
                this.codeAbattementField = value;
                this.RaisePropertyChanged("codeAbattement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string portChargement {
            get {
                return this.portChargementField;
            }
            set {
                this.portChargementField = value;
                this.RaisePropertyChanged("portChargement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int idCargaison {
            get {
                return this.idCargaisonField;
            }
            set {
                this.idCargaisonField = value;
                this.RaisePropertyChanged("idCargaison");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public System.DateTime heureOperation {
            get {
                return this.heureOperationField;
            }
            set {
                this.heureOperationField = value;
                this.RaisePropertyChanged("heureOperation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal qteOperationBigDec {
            get {
                return this.qteOperationBigDecField;
            }
            set {
                this.qteOperationBigDecField = value;
                this.RaisePropertyChanged("qteOperationBigDec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal qtePertesBigDec {
            get {
                return this.qtePertesBigDecField;
            }
            set {
                this.qtePertesBigDecField = value;
                this.RaisePropertyChanged("qtePertesBigDec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int mef {
            get {
                return this.mefField;
            }
            set {
                this.mefField = value;
                this.RaisePropertyChanged("mef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string tpsMefMeg {
            get {
                return this.tpsMefMegField;
            }
            set {
                this.tpsMefMegField = value;
                this.RaisePropertyChanged("tpsMefMeg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public float volMefMeg {
            get {
                return this.volMefMegField;
            }
            set {
                this.volMefMegField = value;
                this.RaisePropertyChanged("volMefMeg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public float qteMefMeg {
            get {
                return this.qteMefMegField;
            }
            set {
                this.qteMefMegField = value;
                this.RaisePropertyChanged("qteMefMeg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public decimal qteMefMegBigDec {
            get {
                return this.qteMefMegBigDecField;
            }
            set {
                this.qteMefMegBigDecField = value;
                this.RaisePropertyChanged("qteMefMegBigDec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string codeBook {
            get {
                return this.codeBookField;
            }
            set {
                this.codeBookField = value;
                this.RaisePropertyChanged("codeBook");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public float remport {
            get {
                return this.remportField;
            }
            set {
                this.remportField = value;
                this.RaisePropertyChanged("remport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public float consoGNL {
            get {
                return this.consoGNLField;
            }
            set {
                this.consoGNLField = value;
                this.RaisePropertyChanged("consoGNL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public float consoCarb {
            get {
                return this.consoCarbField;
            }
            set {
                this.consoCarbField = value;
                this.RaisePropertyChanged("consoCarb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public float quantiteMax {
            get {
                return this.quantiteMaxField;
            }
            set {
                this.quantiteMaxField = value;
                this.RaisePropertyChanged("quantiteMax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public float robUAC {
            get {
                return this.robUACField;
            }
            set {
                this.robUACField = value;
                this.RaisePropertyChanged("robUAC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public float robUAD {
            get {
                return this.robUADField;
            }
            set {
                this.robUADField = value;
                this.RaisePropertyChanged("robUAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public float robUDC {
            get {
                return this.robUDCField;
            }
            set {
                this.robUDCField = value;
                this.RaisePropertyChanged("robUDC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public float quantiteC {
            get {
                return this.quantiteCField;
            }
            set {
                this.quantiteCField = value;
                this.RaisePropertyChanged("quantiteC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public float remportC {
            get {
                return this.remportCField;
            }
            set {
                this.remportCField = value;
                this.RaisePropertyChanged("remportC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public float consoGNLC {
            get {
                return this.consoGNLCField;
            }
            set {
                this.consoGNLCField = value;
                this.RaisePropertyChanged("consoGNLC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public float consoCarbC {
            get {
                return this.consoCarbCField;
            }
            set {
                this.consoCarbCField = value;
                this.RaisePropertyChanged("consoCarbC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public float quantiteMaxC {
            get {
                return this.quantiteMaxCField;
            }
            set {
                this.quantiteMaxCField = value;
                this.RaisePropertyChanged("quantiteMaxC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public float robUACC {
            get {
                return this.robUACCField;
            }
            set {
                this.robUACCField = value;
                this.RaisePropertyChanged("robUACC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public float robUADC {
            get {
                return this.robUADCField;
            }
            set {
                this.robUADCField = value;
                this.RaisePropertyChanged("robUADC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public float robUDCC {
            get {
                return this.robUDCCField;
            }
            set {
                this.robUDCCField = value;
                this.RaisePropertyChanged("robUDCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public float quantiteM {
            get {
                return this.quantiteMField;
            }
            set {
                this.quantiteMField = value;
                this.RaisePropertyChanged("quantiteM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public float remportM {
            get {
                return this.remportMField;
            }
            set {
                this.remportMField = value;
                this.RaisePropertyChanged("remportM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public float consoGNLM {
            get {
                return this.consoGNLMField;
            }
            set {
                this.consoGNLMField = value;
                this.RaisePropertyChanged("consoGNLM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public float consoCarbM {
            get {
                return this.consoCarbMField;
            }
            set {
                this.consoCarbMField = value;
                this.RaisePropertyChanged("consoCarbM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public float quantiteMaxM {
            get {
                return this.quantiteMaxMField;
            }
            set {
                this.quantiteMaxMField = value;
                this.RaisePropertyChanged("quantiteMaxM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public float robUACM {
            get {
                return this.robUACMField;
            }
            set {
                this.robUACMField = value;
                this.RaisePropertyChanged("robUACM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public float robUADM {
            get {
                return this.robUADMField;
            }
            set {
                this.robUADMField = value;
                this.RaisePropertyChanged("robUADM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public float robUDCM {
            get {
                return this.robUDCMField;
            }
            set {
                this.robUDCMField = value;
                this.RaisePropertyChanged("robUDCM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string canalSuez {
            get {
                return this.canalSuezField;
            }
            set {
                this.canalSuezField = value;
                this.RaisePropertyChanged("canalSuez");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string canalPanama {
            get {
                return this.canalPanamaField;
            }
            set {
                this.canalPanamaField = value;
                this.RaisePropertyChanged("canalPanama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string canalMagellan {
            get {
                return this.canalMagellanField;
            }
            set {
                this.canalMagellanField = value;
                this.RaisePropertyChanged("canalMagellan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public System.DateTime dateSuez {
            get {
                return this.dateSuezField;
            }
            set {
                this.dateSuezField = value;
                this.RaisePropertyChanged("dateSuez");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public System.DateTime datePanama {
            get {
                return this.datePanamaField;
            }
            set {
                this.datePanamaField = value;
                this.RaisePropertyChanged("datePanama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public System.DateTime dateMagellan {
            get {
                return this.dateMagellanField;
            }
            set {
                this.dateMagellanField = value;
                this.RaisePropertyChanged("dateMagellan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public int idPositionCtrm {
            get {
                return this.idPositionCtrmField;
            }
            set {
                this.idPositionCtrmField = value;
                this.RaisePropertyChanged("idPositionCtrm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ws.xb.signal")]
    public partial class GetListOperationsOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ListOperations[] listOperationsField;
        
        private ReturnCodeItem[] returnCodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listOperations", IsNullable=true, Order=0)]
        public ListOperations[] listOperations {
            get {
                return this.listOperationsField;
            }
            set {
                this.listOperationsField = value;
                this.RaisePropertyChanged("listOperations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ReturnCode", Namespace="urn:dvt.com")]
        public ReturnCodeItem[] returnCodes {
            get {
                return this.returnCodesField;
            }
            set {
                this.returnCodesField = value;
                this.RaisePropertyChanged("returnCodes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExtractionOperationsWSChannel : FXWIN.Data.Provider.OperationsService.ExtractionOperationsWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExtractionOperationsWSClient : System.ServiceModel.ClientBase<FXWIN.Data.Provider.OperationsService.ExtractionOperationsWS>, FXWIN.Data.Provider.OperationsService.ExtractionOperationsWS {
        
        public ExtractionOperationsWSClient() {
        }
        
        public ExtractionOperationsWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExtractionOperationsWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtractionOperationsWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtractionOperationsWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FXWIN.Data.Provider.OperationsService.GetListOperationsOutput getListOperations(FXWIN.Data.Provider.OperationsService.GetListOperationsInput input) {
            return base.Channel.getListOperations(input);
        }
        
        public System.Threading.Tasks.Task<FXWIN.Data.Provider.OperationsService.GetListOperationsOutput> getListOperationsAsync(FXWIN.Data.Provider.OperationsService.GetListOperationsInput input) {
            return base.Channel.getListOperationsAsync(input);
        }
    }
}
