//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractExposure
    {
        public int Id { get; set; }
        public string FXContractCode { get; set; }
        public Nullable<int> FXContractId { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<decimal> FxHedgeRatio { get; set; }
        public Nullable<decimal> FxHedgeExposure { get; set; }
        public Nullable<decimal> ResultingFxExposure { get; set; }
        public Nullable<decimal> AvailableFxHedge { get; set; }
        public Nullable<decimal> ContractAvailableFxHedgeBrouillonAmount { get; set; }
        public Nullable<decimal> ContractAvailableFxHedgeEnCoursAmount { get; set; }
        public Nullable<decimal> ContractAvailableFxHedgeValidatedAmount { get; set; }
        public Nullable<decimal> CommodityHedgeExposure { get; set; }
        public Nullable<decimal> ContractValidatedAmount { get; set; }
        public Nullable<decimal> ContractEnCoursAmount { get; set; }
        public Nullable<decimal> ContractBrouillonAmount { get; set; }
        public Nullable<decimal> ContractFxExposure { get; set; }
    }
}
