//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionFX
    {
        public int Id { get; set; }
        public string ExecutionCode { get; set; }
        public int FXHedgeId { get; set; }
        public int PurchaseSaleId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int AmountCurrencyId { get; set; }
        public System.DateTime Maturity { get; set; }
        public Nullable<decimal> SpotRate { get; set; }
        public Nullable<decimal> FwdPoint { get; set; }
        public Nullable<decimal> AllIn { get; set; }
        public Nullable<decimal> ExchValue { get; set; }
        public Nullable<int> ExchCurrencyId { get; set; }
        public string Nature { get; set; }
        public string CreationUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModificationUser { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<decimal> ConfirmationNumber { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual FXHedge FXHedge { get; set; }
        public virtual PurchaseSale PurchaseSale { get; set; }
    }
}
