//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formula()
        {
            this.LinkFxContractFormulas = new HashSet<LinkFxContractFormula>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public decimal Gradient { get; set; }
        public int TimeSerieId { get; set; }
        public int ResultantUnitId { get; set; }
        public decimal Constant { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkFxContractFormula> LinkFxContractFormulas { get; set; }
        public virtual TimeSerie TimeSerie { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
