//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class FxContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FxContract()
        {
            this.CommodityHedges = new HashSet<CommodityHedge>();
            this.CommodityHedges1 = new HashSet<CommodityHedge>();
            this.LinkFxContractFormulas = new HashSet<LinkFxContractFormula>();
            this.LinkFxContractSignalContracts = new HashSet<LinkFxContractSignalContract>();
            this.HedgeLegs = new HashSet<HedgeLeg>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int ContractTypeId { get; set; }
        public int IncotermId { get; set; }
        public int PaymentOffset { get; set; }
        public bool MarginSharingBEE { get; set; }
        public bool IsFiftyFifty { get; set; }
        public bool IsSpotContract { get; set; }
        public bool IsMTContract { get; set; }
        public string OrderNumberPrefix { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> BookId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityHedge> CommodityHedges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityHedge> CommodityHedges1 { get; set; }
        public virtual ContractType ContractType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkFxContractFormula> LinkFxContractFormulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkFxContractSignalContract> LinkFxContractSignalContracts { get; set; }
        public virtual Incoterm Incoterm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HedgeLeg> HedgeLegs { get; set; }
        public virtual Book Book { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
