//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXHedge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FXHedge()
        {
            this.ExecutionFXes = new HashSet<ExecutionFX>();
            this.HedgeLegs = new HashSet<HedgeLeg>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int ManagementIntentId { get; set; }
        public int InternalStateId { get; set; }
        public string Comment { get; set; }
        public int QualificationId { get; set; }
        public int CurrencyId { get; set; }
        public int HedgeTypeId { get; set; }
        public int WorkflowStateId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string CreationUser { get; set; }
        public string ModificationUser { get; set; }
        public string Actarus { get; set; }
        public string Notice { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public string MosarRef { get; set; }
        public string Mosar3rdParty { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionFX> ExecutionFXes { get; set; }
        public virtual HedgeType HedgeType { get; set; }
        public virtual InternalState InternalState { get; set; }
        public virtual ManagementIntent ManagementIntent { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual WorkflowState WorkflowState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HedgeLeg> HedgeLegs { get; set; }
    }
}
