//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class FxParameter
    {
        public string Key { get; set; }
        public Nullable<int> IntValue { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public string StringValue { get; set; }
        public Nullable<bool> BoolValue { get; set; }
    }
}
