//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FXWinV2Entities : DbContext
    {
        public FXWinV2Entities()
            : base("name=FXWinV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<CargoState> CargoStates { get; set; }
        public virtual DbSet<CargoType> CargoTypes { get; set; }
        public virtual DbSet<CommodityHedge> CommodityHedges { get; set; }
        public virtual DbSet<ContractExpositionByDateAndSide> ContractExpositionByDateAndSides { get; set; }
        public virtual DbSet<ContractExposure> ContractExposures { get; set; }
        public virtual DbSet<ContractType> ContractTypes { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<ExecutionFX> ExecutionFXes { get; set; }
        public virtual DbSet<Formula> Formulae { get; set; }
        public virtual DbSet<FxContract> FxContracts { get; set; }
        public virtual DbSet<FXHedge> FXHedges { get; set; }
        public virtual DbSet<FxParameter> FxParameters { get; set; }
        public virtual DbSet<FxRole> FxRoles { get; set; }
        public virtual DbSet<FxUser> FxUsers { get; set; }
        public virtual DbSet<HedgeCommoMaturity> HedgeCommoMaturities { get; set; }
        public virtual DbSet<HedgeLeg> HedgeLegs { get; set; }
        public virtual DbSet<HedgeType> HedgeTypes { get; set; }
        public virtual DbSet<Incoterm> Incoterms { get; set; }
        public virtual DbSet<InternalState> InternalStates { get; set; }
        public virtual DbSet<LastUsedExportPomaxParameter> LastUsedExportPomaxParameters { get; set; }
        public virtual DbSet<LastUsedFxImportSignalDataParameter> LastUsedFxImportSignalDataParameters { get; set; }
        public virtual DbSet<LastUsedFxValuationParameter> LastUsedFxValuationParameters { get; set; }
        public virtual DbSet<LinkFxContractFormula> LinkFxContractFormulas { get; set; }
        public virtual DbSet<LinkFxContractSignalContract> LinkFxContractSignalContracts { get; set; }
        public virtual DbSet<LinkLegHedgeCommoHedge> LinkLegHedgeCommoHedges { get; set; }
        public virtual DbSet<LinkType> LinkTypes { get; set; }
        public virtual DbSet<ManagementIntent> ManagementIntents { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<OperationExpositionByDateAndSide> OperationExpositionByDateAndSides { get; set; }
        public virtual DbSet<OperationType> OperationTypes { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<PortType> PortTypes { get; set; }
        public virtual DbSet<PurchaseContract> PurchaseContracts { get; set; }
        public virtual DbSet<PurchaseContractValue> PurchaseContractValues { get; set; }
        public virtual DbSet<PurchaseSale> PurchaseSales { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SharedLayout> SharedLayouts { get; set; }
        public virtual DbSet<SignalContractExclusion> SignalContractExclusions { get; set; }
        public virtual DbSet<Subjacent> Subjacents { get; set; }
        public virtual DbSet<SubjacentType> SubjacentTypes { get; set; }
        public virtual DbSet<SupplyContract> SupplyContracts { get; set; }
        public virtual DbSet<TempSicav> TempSicavs { get; set; }
        public virtual DbSet<TermType> TermTypes { get; set; }
        public virtual DbSet<TimeSerie> TimeSeries { get; set; }
        public virtual DbSet<TimeSerieValue> TimeSerieValues { get; set; }
        public virtual DbSet<UnderlyingTerm> UnderlyingTerms { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<Vessel> Vessels { get; set; }
        public virtual DbSet<WorkflowState> WorkflowStates { get; set; }
        public virtual DbSet<Cargo_AuditTrail> Cargo_AuditTrail { get; set; }
        public virtual DbSet<CommodityHedge_AuditTrail> CommodityHedge_AuditTrail { get; set; }
        public virtual DbSet<ExecutionFX_AuditTrail> ExecutionFX_AuditTrail { get; set; }
        public virtual DbSet<FxHedge_AuditTrail> FxHedge_AuditTrail { get; set; }
        public virtual DbSet<HedgeCommoMaturity_AuditTrail> HedgeCommoMaturity_AuditTrail { get; set; }
        public virtual DbSet<HedgeLeg_AuditTrail> HedgeLeg_AuditTrail { get; set; }
        public virtual DbSet<Operation_AuditTrail> Operation_AuditTrail { get; set; }
        public virtual DbSet<Subjacent_AuditTrail> Subjacent_AuditTrail { get; set; }
        public virtual DbSet<UnderlyingTerm_AuditTrail> UnderlyingTerm_AuditTrail { get; set; }
        public virtual DbSet<VW_CargoView> VW_CargoView { get; set; }
        public virtual DbSet<VW_CommoHedgeWithMaturity> VW_CommoHedgeWithMaturity { get; set; }
        public virtual DbSet<VW_Cube> VW_Cube { get; set; }
        public virtual DbSet<VW_CubeCommodity> VW_CubeCommodity { get; set; }
        public virtual DbSet<VW_CubeFXHedge> VW_CubeFXHedge { get; set; }
        public virtual DbSet<VW_CubeOperation> VW_CubeOperation { get; set; }
        public virtual DbSet<VW_ExportPomax> VW_ExportPomax { get; set; }
        public virtual DbSet<VW_FXHedgeSynthesis> VW_FXHedgeSynthesis { get; set; }
        public virtual DbSet<VW_FxWinUnits> VW_FxWinUnits { get; set; }
        public virtual DbSet<VW_LinkFxContractSignalContract> VW_LinkFxContractSignalContract { get; set; }
        public virtual DbSet<VW_Reporting> VW_Reporting { get; set; }
        public virtual DbSet<VW_SignalContract> VW_SignalContract { get; set; }
        public virtual DbSet<VW_UsersView> VW_UsersView { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<VW_ExportFxHedges> VW_ExportFxHedges { get; set; }
    
        public virtual int compute()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("compute");
        }
    
        public virtual ObjectResult<GetAllFXHedgeSynthesis_Result> GetAllFXHedgeSynthesis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllFXHedgeSynthesis_Result>("GetAllFXHedgeSynthesis");
        }
    
        public virtual ObjectResult<GetReportingView_Result> GetReportingView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReportingView_Result>("GetReportingView");
        }
    
        public virtual ObjectResult<usp_GetErrorInfo_Result> usp_GetErrorInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetErrorInfo_Result>("usp_GetErrorInfo");
        }
    }
}
