//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class HedgeLeg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HedgeLeg()
        {
            this.LinkLegHedgeCommoHedges = new HashSet<LinkLegHedgeCommoHedge>();
        }
    
        public int Id { get; set; }
        public int FXHedgeId { get; set; }
        public int PurchaseSaleId { get; set; }
        public System.DateTime Maturity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> FxContractId { get; set; }
        public Nullable<System.DateTime> UnderlyingMonth { get; set; }
        public Nullable<int> OperationId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string CreationUser { get; set; }
        public string ModificationUser { get; set; }
        public Nullable<int> UnderlyingTermId { get; set; }
        public bool MultipleCargoes { get; set; }
    
        public virtual FxContract FxContract { get; set; }
        public virtual FXHedge FXHedge { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual PurchaseSale PurchaseSale { get; set; }
        public virtual UnderlyingTerm UnderlyingTerm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkLegHedgeCommoHedge> LinkLegHedgeCommoHedges { get; set; }
    }
}
