//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class HedgeCommoMaturity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HedgeCommoMaturity()
        {
            this.LinkLegHedgeCommoHedges = new HashSet<LinkLegHedgeCommoHedge>();
        }
    
        public int Id { get; set; }
        public System.DateTime Maturity { get; set; }
        public decimal Volume { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> FXInitialExpo { get; set; }
        public Nullable<decimal> FXFinalExpo { get; set; }
        public int HedgeCommoId { get; set; }
        public Nullable<bool> MOValidated { get; set; }
        public Nullable<decimal> MtM { get; set; }
        public string CreationUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModificationUser { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual CommodityHedge CommodityHedge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkLegHedgeCommoHedge> LinkLegHedgeCommoHedges { get; set; }
    }
}
