//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastUsedFxValuationParameter
    {
        public int Id { get; set; }
        public string IdGaia { get; set; }
        public System.DateTime PivotDate { get; set; }
        public string DatabasePath { get; set; }
        public string StormFilePath { get; set; }
    }
}
