//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkLegHedgeCommoHedge
    {
        public int Id { get; set; }
        public int HedgeLegId { get; set; }
        public int CommoHedgeId { get; set; }
        public int MaturityId { get; set; }
        public int LinkTypeId { get; set; }
        public int PurchaseSaleId { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public string CreationUser { get; set; }
        public string ModificationUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual CommodityHedge CommodityHedge { get; set; }
        public virtual HedgeCommoMaturity HedgeCommoMaturity { get; set; }
        public virtual HedgeLeg HedgeLeg { get; set; }
        public virtual LinkType LinkType { get; set; }
        public virtual PurchaseSale PurchaseSale { get; set; }
    }
}
