//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operation()
        {
            this.CommodityHedges = new HashSet<CommodityHedge>();
            this.HedgeLegs = new HashSet<HedgeLeg>();
        }
    
        public int Id { get; set; }
        public string OperationSignal { get; set; }
        public Nullable<int> PurchaseContractId { get; set; }
        public Nullable<int> SupplyContractId { get; set; }
        public Nullable<int> PortId { get; set; }
        public System.DateTime OperationDate { get; set; }
        public Nullable<int> VesselId { get; set; }
        public Nullable<int> CargoTypeId { get; set; }
        public Nullable<int> OperationTypeId { get; set; }
        public string PurchaseMiddleOfficeCode { get; set; }
        public string SaleMiddleOfficeCode { get; set; }
        public int CargoId { get; set; }
        public Nullable<int> PurchaseSaleId { get; set; }
        public Nullable<decimal> OperationVolumeM3 { get; set; }
        public Nullable<decimal> EnergyTW0 { get; set; }
        public Nullable<decimal> LostAtSeaM3 { get; set; }
        public Nullable<decimal> LostAtSeaTW0 { get; set; }
        public Nullable<int> CodeAbattement { get; set; }
        public Nullable<int> LoadingPortId { get; set; }
        public Nullable<int> InternalStateId { get; set; }
        public int CurrencyId { get; set; }
        public int CommoUnitId { get; set; }
        public Nullable<System.DateTime> PayementDate { get; set; }
        public Nullable<System.DateTime> PayementDate2 { get; set; }
        public Nullable<decimal> CommoFxExposition { get; set; }
        public Nullable<decimal> ConstantFxExposition { get; set; }
        public Nullable<decimal> CommoExposition { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<int> IsBOValidated { get; set; }
        public Nullable<decimal> CargoFxHedgeRatio { get; set; }
        public Nullable<decimal> CargoResultingFxExposure { get; set; }
        public Nullable<decimal> CargoPhysicalFxExposure { get; set; }
        public Nullable<decimal> CargoValidatedFxHedgeExposure { get; set; }
        public Nullable<decimal> CargoEnCoursFxHedgeExposure { get; set; }
        public Nullable<decimal> CargoBrouillonFxHedgeExposure { get; set; }
        public Nullable<decimal> CargoFxHedgeExposure { get; set; }
        public Nullable<decimal> CargoCommodityHedgeExposure { get; set; }
        public Nullable<System.DateTime> CargoValidatedMaturity { get; set; }
        public Nullable<System.DateTime> CargoBrouillonMaturity { get; set; }
        public Nullable<System.DateTime> CargoEnCoursMaturity { get; set; }
        public Nullable<System.DateTime> CargoFxHedgeMaturity { get; set; }
        public Nullable<bool> HasCargoValidatedMaturityConflict { get; set; }
        public Nullable<bool> HasCargoEnCoursMaturityConflict { get; set; }
        public Nullable<bool> HasCargoBrouillonMaturityConflict { get; set; }
        public Nullable<decimal> ContractPhysicalExposure { get; set; }
        public Nullable<decimal> ContractValidatedAmount { get; set; }
        public Nullable<decimal> ContractBrouillonAmount { get; set; }
        public Nullable<decimal> ContractEnCoursAmount { get; set; }
        public Nullable<decimal> ContractFxExposure { get; set; }
        public Nullable<decimal> ContractAvailableFxHedgeBrouillonAmount { get; set; }
        public Nullable<decimal> ContractAvailableFxHedgeEnCoursAmount { get; set; }
        public Nullable<decimal> ContractAvailableFxHedgeValidatedAmount { get; set; }
        public Nullable<decimal> ContractAvailableFxHedge { get; set; }
        public Nullable<decimal> ContractCommodityHedgeExposure { get; set; }
        public Nullable<decimal> ContractFxHedgeRatio { get; set; }
        public Nullable<decimal> ContractResultingFxExposure { get; set; }
        public Nullable<System.DateTime> ContractValidatedMaturity { get; set; }
        public Nullable<System.DateTime> ContractBrouillonMaturity { get; set; }
        public Nullable<System.DateTime> ContractEnCoursMaturity { get; set; }
        public Nullable<System.DateTime> ContractAvailableFxMaturity { get; set; }
        public Nullable<bool> HasContractValidatedMaturityConflict { get; set; }
        public Nullable<bool> HasContractEnCoursMaturityConflict { get; set; }
        public Nullable<bool> HasContractBrouillonMaturityConflict { get; set; }
        public Nullable<bool> CargoFxHedgeRatioIsError { get; set; }
        public Nullable<bool> ContractFxHedgeRatioIsError { get; set; }
        public Nullable<System.DateTime> ContractAvailableMaturityInConflictCase { get; set; }
        public string CreationUser { get; set; }
        public string ModificationUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual CargoType CargoType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityHedge> CommodityHedges { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HedgeLeg> HedgeLegs { get; set; }
        public virtual OperationType OperationType { get; set; }
        public virtual Port Port { get; set; }
        public virtual Port Port1 { get; set; }
        public virtual PurchaseContract PurchaseContract { get; set; }
        public virtual PurchaseSale PurchaseSale { get; set; }
        public virtual SupplyContract SupplyContract { get; set; }
        public virtual Vessel Vessel { get; set; }
    }
}
