//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DisplayHedgeDate { get; set; }
        public Nullable<System.DateTime> CargoDisplayDate { get; set; }
        public Nullable<System.DateTime> BEEMSDate { get; set; }
    }
}
