//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedLayout
    {
        public int LayoutId { get; set; }
        public string FileName { get; set; }
        public byte[] Content { get; set; }
        public string ScreenName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public bool IsShared { get; set; }
        public bool LastUsedLayout { get; set; }
    
        public virtual FxUser FxUser { get; set; }
    }
}
