//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignalContractExclusion
    {
        public int Id { get; set; }
        public Nullable<int> PurchaseContractId { get; set; }
        public Nullable<int> SupplyContractId { get; set; }
    
        public virtual PurchaseContract PurchaseContract { get; set; }
        public virtual SupplyContract SupplyContract { get; set; }
    }
}
