//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjacent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subjacent()
        {
            this.UnderlyingTerms = new HashSet<UnderlyingTerm>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int SubjacentTypeId { get; set; }
        public Nullable<bool> IsBEEMarginSharing { get; set; }
        public Nullable<int> PurchaseSaleId { get; set; }
        public string CreationUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModificationUser { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<int> BookId { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual SubjacentType SubjacentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnderlyingTerm> UnderlyingTerms { get; set; }
        public virtual Book Book { get; set; }
    }
}
