//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempSicav
    {
        public int Id { get; set; }
        public string FXHedge_Code { get; set; }
        public System.DateTime FXHedge_ExecutionDate { get; set; }
        public string FXHedge_HedgeTypeId { get; set; }
        public string FXHedge_CurrencyId { get; set; }
        public Nullable<decimal> HedgeLeg_Amount { get; set; }
        public string ExecutionFX_ExecutionCode { get; set; }
        public string ExecutionFX_HedgeLeg_PurchaseSaleId { get; set; }
        public string ExecutionFX_Nature { get; set; }
        public Nullable<decimal> ExecutionFX_Amount { get; set; }
        public string ExecutionFX_CurrencyId { get; set; }
        public Nullable<decimal> ExecutionFX_SpotRate { get; set; }
        public Nullable<decimal> ExecutionFX_FwdPoint { get; set; }
        public Nullable<decimal> ExecutionFX_AllIn { get; set; }
        public System.DateTime ExecutionFX_HedgeLeg_Maturity { get; set; }
        public Nullable<decimal> ExecutionFX_ExchValue { get; set; }
        public string ExecutionFX_ExchCurrencyId { get; set; }
        public string FXhedge_Comment { get; set; }
        public string FXhedge_Notice { get; set; }
        public string FXhedge_Actarus { get; set; }
        public string HedgeLeg_FxContractId { get; set; }
        public Nullable<System.DateTime> HedgeLeg_UnderlyingMonth { get; set; }
        public string HedgeLeg_OperationId { get; set; }
        public string FXhedge_ManagementIntentId { get; set; }
    }
}
