//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSerieValue
    {
        public int Id { get; set; }
        public int TimeSerieId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Value { get; set; }
    
        public virtual TimeSerie TimeSerie { get; set; }
    }
}
