//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnderlyingTerm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnderlyingTerm()
        {
            this.CommodityHedges = new HashSet<CommodityHedge>();
            this.HedgeLegs = new HashSet<HedgeLeg>();
        }
    
        public int Id { get; set; }
        public int UnderlyingId { get; set; }
        public string Label { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int CurrencyId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Maturity { get; set; }
        public Nullable<int> IsBOValidated { get; set; }
        public string CreationUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModificationUser { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityHedge> CommodityHedges { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HedgeLeg> HedgeLegs { get; set; }
        public virtual Subjacent Subjacent { get; set; }
    }
}
