//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vessel()
        {
            this.Operations = new HashSet<Operation>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> GrossCapacity { get; set; }
        public Nullable<decimal> Uilage { get; set; }
        public Nullable<decimal> VolUponArrival { get; set; }
        public Nullable<decimal> Laden { get; set; }
        public Nullable<decimal> Ballast { get; set; }
        public Nullable<decimal> IdleLaden { get; set; }
        public Nullable<decimal> IdleBallast { get; set; }
        public Nullable<decimal> GaranteeSpeed { get; set; }
        public Nullable<decimal> ConsoGaranteeSpeedLaden { get; set; }
        public Nullable<decimal> ConsoGaranteeSpeedBallast { get; set; }
        public Nullable<decimal> ConsoMaxSpeed { get; set; }
        public Nullable<decimal> ConsoIdle { get; set; }
        public Nullable<decimal> EcoSpeedBallast { get; set; }
        public Nullable<decimal> EcoSpeedLaden { get; set; }
        public Nullable<decimal> MaxSpeed { get; set; }
        public Nullable<decimal> CharterHireCapex { get; set; }
        public Nullable<decimal> CharterHireOpex { get; set; }
        public Nullable<decimal> SuezLaden { get; set; }
        public Nullable<decimal> SuezBallast { get; set; }
        public Nullable<decimal> MagellanLaden { get; set; }
        public Nullable<decimal> MagellanBallast { get; set; }
        public int BunkerFuelTypeId { get; set; }
        public Nullable<decimal> ConsoBunkerFuelLoadingDay { get; set; }
        public Nullable<decimal> ConsoBunkerFuelUnloadingDay { get; set; }
        public Nullable<decimal> PilotLaden { get; set; }
        public Nullable<decimal> PilotBallast { get; set; }
        public Nullable<int> InventId { get; set; }
        public Nullable<bool> IsInventSelected { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation> Operations { get; set; }
    }
}
