//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CubeFXHedge
    {
        public long Id { get; set; }
        public Nullable<int> years { get; set; }
        public Nullable<int> Mois { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> HedgeLegId { get; set; }
        public Nullable<int> FxContractId { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<int> MaturityDay { get; set; }
        public Nullable<int> MaturityMonth { get; set; }
        public Nullable<int> MaturityYear { get; set; }
        public Nullable<int> UnderlyingMonth { get; set; }
        public Nullable<int> UnderlyingYear { get; set; }
        public string FxContractCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AvailableFxHedge { get; set; }
        public string CargoCode { get; set; }
        public Nullable<decimal> PhysicalExposure { get; set; }
    }
}
