//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CubeOperation
    {
        public int OperationId { get; set; }
        public Nullable<int> OperationDateMonth { get; set; }
        public Nullable<int> OperationDateYear { get; set; }
        public string CargoCode { get; set; }
        public Nullable<int> PurchaseContractId { get; set; }
        public string FxContractCode { get; set; }
        public Nullable<decimal> OperationFxHedgeExposure { get; set; }
        public Nullable<decimal> OperationCommodityHedgeExposure { get; set; }
        public Nullable<decimal> OperationPhysicalExposure { get; set; }
        public Nullable<decimal> OperationFxHedgeRatio { get; set; }
        public Nullable<decimal> OperationResultingExposure { get; set; }
    }
}
