//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CargoView
    {
        public int CargoId { get; set; }
        public string Code { get; set; }
        public string CargoState { get; set; }
        public System.DateTime CargoLoadingDate { get; set; }
        public string PurchaseContract { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public Nullable<decimal> PurchaseAmount2 { get; set; }
        public string PurchaseCargoType { get; set; }
        public Nullable<int> PurchaseCodeAbattement { get; set; }
        public Nullable<decimal> PurchaseCommoExposition { get; set; }
        public string PurchaseUnitCode { get; set; }
        public Nullable<decimal> PurchaseConstantFxExposition { get; set; }
        public string PurchaseCurrency { get; set; }
        public Nullable<decimal> PurchaseEnergyTW0 { get; set; }
        public string PurchaseOperationInternalState { get; set; }
        public string PurchaseLoadingPort { get; set; }
        public Nullable<decimal> PurchaseLostAtSeaM3 { get; set; }
        public Nullable<decimal> PurchaseLostAtSeaTW0 { get; set; }
        public Nullable<System.DateTime> PurchaseOperationDate { get; set; }
        public string PurchaseOperationSignal { get; set; }
        public string PurchaseOperationType { get; set; }
        public Nullable<decimal> PurchaseOperationVolumeM3 { get; set; }
        public Nullable<System.DateTime> PurchasePayementDate { get; set; }
        public Nullable<System.DateTime> PurchasePayementDate2 { get; set; }
        public string PurchaseMiddleOfficeCode { get; set; }
        public string PurchaseVesselCode { get; set; }
        public Nullable<decimal> PurchaseEnergyMMBtu { get; set; }
        public Nullable<int> PurchaseBOValidated { get; set; }
        public Nullable<decimal> PurchaseCargoFxHedgeRatio { get; set; }
        public Nullable<decimal> PurchaseCargoResultingFxExposure { get; set; }
        public Nullable<decimal> PurchaseCargoPhysicalFxExposure { get; set; }
        public Nullable<decimal> PurchaseCargoFxHedgeExposure { get; set; }
        public Nullable<System.DateTime> PurchaseCargoFxHedgeMaturity { get; set; }
        public Nullable<decimal> PurchaseCargoCommodityHedgeExposure { get; set; }
        public string SaleContract { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<decimal> SaleAmount2 { get; set; }
        public string SaleCargoType { get; set; }
        public Nullable<int> SaleCodeAbattement { get; set; }
        public Nullable<decimal> SaleCommoExposition { get; set; }
        public string SaleUnitCode { get; set; }
        public Nullable<decimal> SaleConstantFxExposition { get; set; }
        public string SaleCurrency { get; set; }
        public Nullable<decimal> SaleEnergyTW0 { get; set; }
        public string SaleOperationInternalState { get; set; }
        public string SaleLoadingPort { get; set; }
        public Nullable<decimal> SaleLostAtSeaM3 { get; set; }
        public Nullable<decimal> SaleLostAtSeaTW0 { get; set; }
        public Nullable<System.DateTime> SaleOperationDate { get; set; }
        public string SaleOperationSignal { get; set; }
        public string SaleOperationType { get; set; }
        public Nullable<decimal> SaleOperationVolumeM3 { get; set; }
        public Nullable<System.DateTime> SalePayementDate { get; set; }
        public Nullable<System.DateTime> SalePayementDate2 { get; set; }
        public string SaleMiddleOfficeCode { get; set; }
        public string SaleVesselCode { get; set; }
        public Nullable<decimal> SaleEnergyMMBtu { get; set; }
        public Nullable<int> SaleBOValidated { get; set; }
        public Nullable<decimal> SaleCargoFxHedgeRatio { get; set; }
        public Nullable<decimal> SaleCargoResultingFxExposure { get; set; }
        public Nullable<decimal> SaleCargoPhysicalFxExposure { get; set; }
        public Nullable<decimal> SaleCargoFxHedgeExposure { get; set; }
        public Nullable<System.DateTime> SaleCargoFxHedgeMaturity { get; set; }
        public Nullable<decimal> SaleCargoCommodityHedgeExposure { get; set; }
    }
}
