//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CubeCommodity
    {
        public long Id { get; set; }
        public Nullable<int> OperationId { get; set; }
        public string CargoCode { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string FxContractCode { get; set; }
        public Nullable<int> FxContractId { get; set; }
        public Nullable<int> CommodityHedgeId { get; set; }
        public string Code { get; set; }
        public Nullable<int> HedgeCommoMaturityId { get; set; }
        public Nullable<int> HedgeCommoMaturityMonth { get; set; }
        public Nullable<int> HedgeCommoMaturityYear { get; set; }
        public Nullable<int> CommodityHedgeFxContractId { get; set; }
        public Nullable<int> CommodityHedgeOperationId { get; set; }
        public Nullable<decimal> MtM { get; set; }
    }
}
