//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ExportFxHedges
    {
        public int Id { get; set; }
        public string SIAM { get; set; }
        public string Code { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PurchaseSale { get; set; }
        public Nullable<decimal> FwdPoint { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public Nullable<System.DateTime> UnderlyingMonth { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public string Book { get; set; }
        public Nullable<decimal> SpotRate { get; set; }
        public Nullable<decimal> ForwardPoints { get; set; }
        public Nullable<decimal> FxRate { get; set; }
        public Nullable<int> IdSIAM { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string FxCreationUser { get; set; }
        public string Status { get; set; }
        public int StatusId { get; set; }
    }
}
