//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXWIN.Data.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ExportPomax
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PurchaseSale { get; set; }
        public Nullable<decimal> FwdPoint { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public Nullable<System.DateTime> UnderlyingMonth { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public string Book { get; set; }
        public Nullable<int> Underlying { get; set; }
    }
}
